### Características de la práctica

En esta práctica el alumno aplica los conceptos de composición y herencia en Python.

### La clase `Libro`

La clase `Libro` contiene información sobre
un determinado libro, tal como el nombre del autor, el título, y el
precio base. Además, también posee información sobre el porcentaje de
IVA que se aplica para calcular su precio final. Nótese que el
porcentaje de IVA a aplicar es el mismo y es compartido por todos los
libros, siendo su valor inicial el 10.0%. Todos los atributos serán privados.

Se pide implementar:

~~~ {.py}
def __init__(self, autor, titulo, precio_base)
~~~

> Construye un objeto `Libro`. Recibe como parámetros, en el siguiente
> orden, el nombre del autor, el título, y el precio base del libro.

~~~ {.py}
▶ def autor(self)
▶ def titulo(self)
▶ def precio_base(self)
~~~

> Devuelven los valores correspondientes almacenados en el objeto (puedes usar decoradores, pero no es obligatorio).

~~~ {.py}
▶ def precio_final(self)
~~~

> Devuelve el precio final del libro, incluyendo el IVA, según la
> siguiente ecuación.
>> $\mathit{PF}=\mathit{PB}+\mathit{PB}\times\mathit{IVA}\div100$

~~~ {.py}
▶ def __str__(self)
~~~

> Devuelve la representación textual del objeto, según el formato del
> siguiente ejemplo:
>> ~~~
>> (Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03)
>> ~~~

~~~ {.py}
▶ def __eq__(self,other)
~~~

> Compara el libro actual (self) con el libro recibido como parámetro (other). Dos libros serán iguales si los son el autor y el titulo, independientemente de mayúsculas y minúsculas (*HINT*: usa lower()).


In [1]:
class Libro:
    iva = 10.0  # Porcentaje de IVA compartido por todos los libros

    def __init__(self, autor, titulo, precio_base):
        self.__autor = autor
        self.__titulo = titulo
        self.__precio_base = precio_base

    @property
    def autor(self):
        return self.__autor

    @property
    def titulo(self):
        return self.__titulo

    @property
    def precio_base(self):
        return self.__precio_base

    def precio_final(self):
        return self.__precio_base + self.__precio_base * self.iva / 100

    def __str__(self):
        pf = self.precio_final()
        return f"({self.__autor}; {self.__titulo}; {self.__precio_base:.2f}; {self.iva:.1f}%; {pf:.2f})"

    def __eq__(self, other):
        if isinstance(other, Libro):
            return (self.__autor.lower() == other.__autor.lower() and
                    self.__titulo.lower() == other.__titulo.lower())
        return False

In [3]:
# Crea tres objetos de la clase libro:
libro1 = Libro('Isaac Asimov', 'La Fundación', 7.30)
libro2 = Libro('isaac AsimOV', 'la fundación', 38)
libro3 = Libro('isaac AsimOV', 'la fundación', 38)

# Muestra los objetos por pantalla
print(libro1)
print(libro2)
print(libro3)

# Muestra el IVA
print("IVA:", Libro.iva)

# Compara los tres objetos entre ellos para ver si son iguales dos a dos
print("libro1 == libro2:", libro1 == libro2)
print("libro1 == libro3:", libro1 == libro3)
print("libro2 == libro3:", libro2 == libro3)

(Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03)
(isaac AsimOV; la fundación; 38.00; 10.0%; 41.80)
(isaac AsimOV; la fundación; 38.00; 10.0%; 41.80)
IVA: 10.0
libro1 == libro2: True
libro1 == libro3: True
libro2 == libro3: True


### La clase `Libreria`

La clase `Libreria` almacenará varios objetos `Libro` en una lista privada.

Se pide implementar:

~~~ {.py}
def __init__(self)
~~~

> Construye una librería vacía.

~~~ {.py}
def add_libro(self, autor, titulo, precio_base)
~~~

> Crea un libro y lo añade a la librería. Si ya existe un libro con el mismo autor y título, se reemplaza por el nuevo.

~~~ {.py}
def rem_libro(self, autor, titulo)
~~~

> Elimina el libro indicado si existe. Si no existe, se puede mostrar un mensaje por pantalla.

~~~ {.py}
def get_precio_final(self, autor, titulo)
~~~

> Devuelve el precio final del libro indicado. Si no existe, devuelve `0.0`.

~~~ {.py}
def __str__(self)
~~~

> Devuelve la representación textual del objeto, según el formato del
> siguiente ejemplo (sin considerar los saltos de línea):
>> ~~~
>> [(George Orwell; 1984; 6.20; 10.0%; 6.82),
>>  (Philip K. Dick; ¿Sueñan los androides con ovejas eléctricas?; 3.50; 10.0%; 3.85),
>>  (Isaac Asimov; Fundación e Imperio; 9.40; 10.0%; 10.34),
>>  (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
>>  (Aldous Huxley; Un Mundo Feliz; 6.50; 10.0%; 7.15),
>>  (Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03), 
>>  (William Gibson; Neuromante; 8.30; 10.0%; 9.13),
>>  (Isaac Asimov; Segunda Fundación; 8.10; 10.0%; 8.91),
>>  (Isaac Newton; Arithmetica Universalis; 10.50; 10.0%; 11.55)]
>> ~~~


Recomendación: puedes crear un metodo privado `__buscar_libro(...)` para localizar la posición de un libro dentro de la lista.

In [4]:
class Libreria:
    def __init__(self):
        self.__libros = []

    def __buscar_libro(self, autor, titulo):
        for i, libro in enumerate(self.__libros):
            if libro.autor.lower() == autor.lower() and libro.titulo.lower() == titulo.lower():
                return i
        return -1

    def add_libro(self, autor, titulo, precio_base):
        index = self.__buscar_libro(autor, titulo)
        libro = Libro(autor, titulo, precio_base)
        if index != -1:
            self.__libros[index] = libro
        else:
            self.__libros.append(libro)

    def rem_libro(self, autor, titulo):
        index = self.__buscar_libro(autor, titulo)
        if index != -1:
            del self.__libros[index]
        else:
            print(f"Libro '{titulo}' de '{autor}' no encontrado.")

    def get_precio_final(self, autor, titulo):
        index = self.__buscar_libro(autor, titulo)
        if index != -1:
            return self.__libros[index].precio_final()
        return 0.0

    def __str__(self):
        return "[" + ",\n ".join(str(libro) for libro in self.__libros) + "]"

### Uso la de la clase librería

Crea una libreria y anade los siguientes libros:

> ~~~
> ("george orwell", "1984", 8.20)
> ("Philip K. Dick", "¿Suenan los androides con ovejas electricas?", 3.50)
> ("Isaac Asimov", "Fundacion e Imperio", 9.40)
> ("Ray Bradbury", "Fahrenheit 451", 7.40)
> ("Aldous Huxley", "Un Mundo Feliz", 6.50)
> ("Isaac Asimov", "La Fundacion", 7.30)
> ("George Orwell", "1984", 6.20)
> ~~~

Observa que el ultimo libro debe reemplazar al primero, porque tienen el mismo autor y titulo.

Al mostrar la libreria, deberia aparecer una salida equivalente a esta:

> ~~~
> [(George Orwell; 1984; 6.20; 10.0%; 6.82),
>  (Philip K. Dick; ¿Suenan los androides con ovejas electricas?; 3.50; 10.0%; 3.85),
>  (Isaac Asimov; Fundacion e Imperio; 9.40; 10.0%; 10.34),
>  (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
>  (Aldous Huxley; Un Mundo Feliz; 6.50; 10.0%; 7.15),
>  (Isaac Asimov; La Fundacion; 7.30; 10.0%; 8.03)]
> ~~~

In [5]:
# Crea una libreria, anade los libros anteriores y muestra la libreria
libreria = Libreria()
libreria.add_libro("george orwell", "1984", 8.20)
libreria.add_libro("Philip K. Dick", "¿Suenan los androides con ovejas electricas?", 3.50)
libreria.add_libro("Isaac Asimov", "Fundacion e Imperio", 9.40)
libreria.add_libro("Ray Bradbury", "Fahrenheit 451", 7.40)
libreria.add_libro("Aldous Huxley", "Un Mundo Feliz", 6.50)
libreria.add_libro("Isaac Asimov", "La Fundacion", 7.30)
libreria.add_libro("George Orwell", "1984", 6.20)  # Reemplaza el primero
print(libreria)

[(George Orwell; 1984; 6.20; 10.0%; 6.82),
 (Philip K. Dick; ¿Suenan los androides con ovejas electricas?; 3.50; 10.0%; 3.85),
 (Isaac Asimov; Fundacion e Imperio; 9.40; 10.0%; 10.34),
 (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
 (Aldous Huxley; Un Mundo Feliz; 6.50; 10.0%; 7.15),
 (Isaac Asimov; La Fundacion; 7.30; 10.0%; 8.03)]


A continuacion, elimina los siguientes libros:

> ~~~
> ("George Orwell", "1984")
> ("Aldous Huxley", "Un Mundo Feliz")
> ("James Gosling", "The Java Language Specification")
> ~~~

Tras esas operaciones, la libreria deberia quedar equivalente a:

> ~~~
> [(Philip K. Dick; ¿Suenan los androides con ovejas electricas?; 3.50; 10.0%; 3.85),
>  (Isaac Asimov; Fundacion e Imperio; 9.40; 10.0%; 10.34),
>  (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
>  (Isaac Asimov; La Fundacion; 7.30; 10.0%; 8.03)]
> ~~~

In [6]:
# Elimina los libros anteriores y muestra de nuevo la libreria
libreria.rem_libro("George Orwell", "1984")
libreria.rem_libro("Aldous Huxley", "Un Mundo Feliz")
libreria.rem_libro("James Gosling", "The Java Language Specification")
print(libreria)

Libro 'The Java Language Specification' de 'James Gosling' no encontrado.
[(Philip K. Dick; ¿Suenan los androides con ovejas electricas?; 3.50; 10.0%; 3.85),
 (Isaac Asimov; Fundacion e Imperio; 9.40; 10.0%; 10.34),
 (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
 (Isaac Asimov; La Fundacion; 7.30; 10.0%; 8.03)]


Finalmente, muestra el precio final de los siguientes libros:

> ~~~
> get_precio_final("George Orwell", "1984") -> 0.0
> get_precio_final("Philip K. Dick", "¿Suenan los androides con ovejas electricas?") -> 3.85
> get_precio_final("isaac asimov", "fundacion e imperio") -> 10.34
> get_precio_final("Aldous Huxley", "Un Mundo Feliz") -> 0.0
> get_precio_final("Isaac Asimov", "La Fundacion") -> 8.03
> ~~~

Fijate en que algunas consultas usan mayusculas y minusculas distintas.

In [7]:
# Escribe el codigo que muestre las consultas anteriores
print(f'get_precio_final("George Orwell", "1984") -> {libreria.get_precio_final("George Orwell", "1984")}')
print(f'get_precio_final("Philip K. Dick", "¿Suenan los androides con ovejas electricas?") -> {libreria.get_precio_final("Philip K. Dick", "¿Suenan los androides con ovejas electricas?")}')
print(f'get_precio_final("isaac asimov", "fundacion e imperio") -> {libreria.get_precio_final("isaac asimov", "fundacion e imperio")}')
print(f'get_precio_final("Aldous Huxley", "Un Mundo Feliz") -> {libreria.get_precio_final("Aldous Huxley", "Un Mundo Feliz")}')
print(f'get_precio_final("Isaac Asimov", "La Fundacion") -> {libreria.get_precio_final("Isaac Asimov", "La Fundacion")}')

get_precio_final("George Orwell", "1984") -> 0.0
get_precio_final("Philip K. Dick", "¿Suenan los androides con ovejas electricas?") -> 3.85
get_precio_final("isaac asimov", "fundacion e imperio") -> 10.34
get_precio_final("Aldous Huxley", "Un Mundo Feliz") -> 0.0
get_precio_final("Isaac Asimov", "La Fundacion") -> 8.03


### Ampliacion opcional: La clase `LibroOferta`

La clase `LibroOferta` deriva de la clase `Libro`, por lo que contiene información sobre un determinado libro, pero además, permite especificar un determinado porcentaje de descuento (atributo privado), que será aplicado al **precio base** al calcular el precio final del libro.
	
~~~ {.py}
▶ def __init__(self,...)
~~~

> Construye un objeto `LibroOferta`. Recibe como parámetros, en el
> siguiente orden, el nombre del autor, el título, el precio base y el
> porcentaje de descuento del libro.

~~~ {.py}
▶ def descuento(self)
~~~

> Devuelve el porcentaje de descuento del libro.

~~~ {.py}
▶ def precio_final(self)
~~~

> Devuelve el precio final del libro, aplicando el descuento al precio
> base, e incluyendo el IVA, según las siguientes ecuaciones.

>> $\mathit{PX}=\mathit{PB}-\mathit{PB}\times\mathit{Descuento}\div100$

>> $\mathit{PF}=\mathit{PX}+\mathit{PX}\times\mathit{IVA}\div100$

~~~ {.py}
▶ def __str__(self)
~~~

> Devuelve la representación textual del objeto, según el formato del
> siguiente ejemplo:

>> ~~~
>> (Isaac Asimov; La Fundación; 7.30; 20.0%; 5.84; 10.0%; 6.424)
>> ~~~



In [8]:
# Opcional: define la clase LibroOferta y prueba algun ejemplo
class LibroOferta(Libro):
    def __init__(self, autor, titulo, precio_base, descuento):
        super().__init__(autor, titulo, precio_base)
        self.__descuento = descuento

    @property
    def descuento(self):
        return self.__descuento

    def precio_final(self):
        px = self._Libro__precio_base - self._Libro__precio_base * self.__descuento / 100
        return px + px * self.iva / 100

    def __str__(self):
        px = self._Libro__precio_base - self._Libro__precio_base * self.__descuento / 100
        pf = self.precio_final()
        return f"({self._Libro__autor}; {self._Libro__titulo}; {self._Libro__precio_base:.2f}; {self.__descuento:.1f}%; {px:.3f}; {self.iva:.1f}%; {pf:.3f})"

# Prueba
libro_oferta = LibroOferta('Isaac Asimov', 'La Fundación', 7.30, 20.0)
print(libro_oferta)
print('Descuento:', libro_oferta.descuento)
print('Precio final:', libro_oferta.precio_final())

(Isaac Asimov; La Fundación; 7.30; 20.0%; 5.840; 10.0%; 6.424)
Descuento: 20.0
Precio final: 6.4239999999999995
